icon: ".github/images/icon.png"
screenshots:
  - ".github/images/attribouter-contributors.png"
  - ".github/images/attribouter-contributor.png"
  - ".github/images/attribouter-licenses.png"
  - ".github/images/attribouter-license.png"
  - ".github/images/attribouter-night.gif"
