name: Deploy

on:
  release:
    types: [published]

jobs:
  gplay-build:
    name: "Deploy APK"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Set up OpenJDK 1.8
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'
      - name: Gradle Build / APK
        run: ./gradlew assemble
      - uses: Shopify/upload-to-release@master
        name: Upload APK to Release
        with:
          name: attribouter.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          repo-token: ${{ secrets.GITHUB_TOKEN }}